services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Basilicom\DataQualityBundle\Controller\:
        resource: "../../Controller"
        public: true
        tags: [ "controller.service_arguments" ]

    Basilicom\DataQualityBundle\Command\:
        resource: "../../Command"
        public: true
        tags: [ "command.service_arguments" ]

    Basilicom\DataQualityBundle\Tools\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('DataQualityBundle')"

    Basilicom\DataQualityBundle\Definition\:
        resource: "../../Definition/*"
        exclude:
            - "../../Definition/AbstractDefinition.php"

    Basilicom\DataQualityBundle\DefinitionsCollection\DefinitionsCollection:
        public: true

    Basilicom\DataQualityBundle\DefinitionsCollection\Factory\FieldDefinitionFactory:
        public: true
        arguments:
            $container: "@service_container"

    Basilicom\DataQualityBundle\Service\DataQualityService:
        public: true

    Basilicom\DataQualityBundle\Provider\DataQualityProvider:
        public: true

    Basilicom\DataQualityBundle\EventSubscriber\:
        resource: "../../EventSubscriber/*"
        tags: [ "kernel.event_subscriber" ]

    #
    # custom Renderer
    #
    custom_renderer.data_quality_config:
        class: Basilicom\DataQualityBundle\Model\Renderer\DataQualityConfigRenderer
        public: true

    #
    # option providers
    #
    options_provider.object_classes:
        class: Basilicom\DataQualityBundle\Model\Provider\ObjectClassesProvider
        public: true

    options_provider.object_fields:
        class: Basilicom\DataQualityBundle\Model\Provider\ObjectFieldsProvider
        public: true

    options_provider.definitions:
        class: Basilicom\DataQualityBundle\Model\Provider\DefinitionsProvider
        public: true
